### ISSUE TITLE
Nullable dates

### ISSUE THREAD

**Issue by mcarrera** [Justbeingjustin/lending-club-csharp#1]
When getting detailed notes, I get an error deserializing the JSON.
I believe those 2 properties should be nullable:

 public DateTime nextPaymentDate { get; set; }
 public DateTime issueDate { get; set; }

**Comment by Justbeingjustin** [comment]
Hello @mcarrera! Thanks for reporting this issue. I uploaded a new package on NuGet with a fix. Try installing version 5.0.2.

```Install-Package lending-club-csharp -Version 5.0.2```

Let me know if you run into any other issues. Thanks again.
